# .pre-commit-config.yaml

# isort
- repo: https://github.com/pycqa/isort
  rev: 5.7.0
  hooks:
  - id: isort
    args:
      - "--profile"
      - "black"

# black
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
    - id: black


# flake8
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: flake8
      args:
        - "--max-line-length=88"
        - "--max-complexity=18"
        - "--select=B,C,E,F,W,T4,B9"
        - "--ignore=E203,E266,E501,W503,F403,F401,E402"

